<?php

return [
    [
        'key'   => 'cms',
        'name'  => 'cms::app.acl.cms',
        'route' => 'admin.cms.pages.index',
        'sort'  => 2,
    ], [
        'key'   => 'cms.pages',
        'name'  => 'cms::app.acl.pages',
        'route' => ['admin.cms.pages.index', 'admin.cms.api.pages.index', 'admin.cms.api.pages.show'],
        'sort'  => 1,
    ], [
        'key'   => 'cms.pages.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.pages.create', 'admin.cms.pages.store', 'admin.cms.api.pages.store'],
        'sort'  => 2,
    ], [
        'key'   => 'cms.pages.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => [
            'admin.cms.pages.edit',
            'admin.cms.pages.update',
            'admin.cms.pages.builder',
            'admin.cms.pages.builder.update',
            'admin.cms.builder.layout-preview',
            'admin.cms.api.pages.update',
            'admin.cms.api.pages.builder',
        ],
        'sort'  => 3,
    ], [
        'key'   => 'cms.pages.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => ['admin.cms.pages.delete', 'admin.cms.api.pages.destroy'],
        'sort'  => 4,
    ], [
        'key'   => 'cms.nav-menus',
        'name'  => 'cms::app.menu.nav-menus',
        'route' => ['admin.cms.nav-menus.index', 'admin.cms.api.nav-menus.index', 'admin.cms.api.nav-menus.show'],
        'sort'  => 5,
    ], [
        'key'   => 'cms.nav-menus.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.nav-menus.create', 'admin.cms.nav-menus.store'],
        'sort'  => 1,
    ], [
        'key'   => 'cms.nav-menus.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => [
            'admin.cms.nav-menus.edit',
            'admin.cms.nav-menus.update',
            'admin.cms.nav-menus.items.index',
            'admin.cms.nav-menus.items.create',
            'admin.cms.nav-menus.items.store',
            'admin.cms.nav-menus.items.edit',
            'admin.cms.nav-menus.items.update',
        ],
        'sort'  => 2,
    ], [
        'key'   => 'cms.nav-menus.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => [
            'admin.cms.nav-menus.delete',
            'admin.cms.nav-menus.items.delete',
        ],
        'sort'  => 3,
    ], [
        'key'   => 'cms.nav-menus.restore',
        'name'  => 'cms::app.acl.restore',
        'route' => [
            'admin.cms.nav-menus.restore',
            'admin.cms.nav-menus.items.restore',
        ],
        'sort'  => 4,
    ], [
        'key'   => 'cms.nav-menus.forceDelete',
        'name'  => 'cms::app.acl.forceDelete',
        'route' => [
            'admin.cms.nav-menus.forceDelete',
            'admin.cms.nav-menus.items.forceDelete',
        ],
        'sort'  => 5,
    ],
    [
        'key'   => 'cms.blog-posts',
        'name'  => 'cms::app.menu.blog-posts',
        'route' => 'admin.cms.blog-posts.index',
        'sort'  => 10,
    ],
    [
        'key'   => 'cms.blog-posts.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.blog-posts.create', 'admin.cms.blog-posts.store'],
        'sort'  => 1,
    ],
    [
        'key'   => 'cms.blog-posts.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => ['admin.cms.blog-posts.edit', 'admin.cms.blog-posts.update'],
        'sort'  => 2,
    ],
    [
        'key'   => 'cms.blog-posts.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => ['admin.cms.blog-posts.delete', 'admin.cms.blog-posts.restore', 'admin.cms.blog-posts.forceDelete'],
        'sort'  => 3,
    ],
    [
        'key'   => 'cms.blog-posts.restore',
        'name'  => 'cms::app.acl.restore',
        'route' => 'admin.cms.blog-posts.restore',
        'sort'  => 4,
    ],
    [
        'key'   => 'cms.blog-posts.forceDelete',
        'name'  => 'cms::app.acl.forceDelete',
        'route' => 'admin.cms.blog-posts.forceDelete',
        'sort'  => 5,
    ],
    [
        'key'   => 'cms.contact-messages',
        'name'  => 'cms::app.acl.contact-messages',
        'route' => 'admin.cms.contact-messages.index',
        'sort'  => 11,
    ],
    [
        'key'   => 'cms.contact-messages.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => 'admin.cms.contact-messages.delete',
        'sort'  => 1,
    ],
    [
        'key'   => 'cms.case-study-categories',
        'name'  => 'cms::app.menu.case-study-categories',
        'route' => ['admin.cms.case-study-categories.index', 'admin.cms.api.case-study-categories.index', 'admin.cms.api.case-study-categories.show'],
        'sort'  => 12,
    ],
    [
        'key'   => 'cms.case-study-categories.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.case-study-categories.create', 'admin.cms.case-study-categories.store', 'admin.cms.api.case-study-categories.store'],
        'sort'  => 1,
    ],
    [
        'key'   => 'cms.case-study-categories.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => ['admin.cms.case-study-categories.edit', 'admin.cms.case-study-categories.update', 'admin.cms.api.case-study-categories.update'],
        'sort'  => 2,
    ],
    [
        'key'   => 'cms.case-study-categories.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => ['admin.cms.case-study-categories.delete', 'admin.cms.api.case-study-categories.destroy'],
        'sort'  => 3,
    ],
    [
        'key'   => 'cms.case-study-categories.restore',
        'name'  => 'cms::app.acl.restore',
        'route' => 'admin.cms.case-study-categories.restore',
        'sort'  => 4,
    ],
    [
        'key'   => 'cms.case-study-categories.forceDelete',
        'name'  => 'cms::app.acl.forceDelete',
        'route' => 'admin.cms.case-study-categories.forceDelete',
        'sort'  => 5,
    ],
    [
        'key'   => 'cms.case-studies',
        'name'  => 'cms::app.menu.case-studies',
        'route' => ['admin.cms.case-studies.index', 'admin.cms.api.case-studies.index', 'admin.cms.api.case-studies.show'],
        'sort'  => 13,
    ],
    [
        'key'   => 'cms.case-studies.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.case-studies.create', 'admin.cms.case-studies.store', 'admin.cms.api.case-studies.store'],
        'sort'  => 1,
    ],
    [
        'key'   => 'cms.case-studies.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => ['admin.cms.case-studies.edit', 'admin.cms.case-studies.update', 'admin.cms.api.case-studies.update'],
        'sort'  => 2,
    ],
    [
        'key'   => 'cms.case-studies.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => ['admin.cms.case-studies.delete', 'admin.cms.api.case-studies.destroy'],
        'sort'  => 3,
    ],
    [
        'key'   => 'cms.case-studies.restore',
        'name'  => 'cms::app.acl.restore',
        'route' => 'admin.cms.case-studies.restore',
        'sort'  => 4,
    ],
    [
        'key'   => 'cms.case-studies.forceDelete',
        'name'  => 'cms::app.acl.forceDelete',
        'route' => 'admin.cms.case-studies.forceDelete',
        'sort'  => 5,
    ],
    [
        'key'   => 'cms.service-types',
        'name'  => 'cms::app.menu.service-types',
        'route' => ['admin.cms.service-types.index', 'admin.cms.api.service-types.index', 'admin.cms.api.service-types.show'],
        'sort'  => 14,
    ],
    [
        'key'   => 'cms.service-types.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.service-types.create', 'admin.cms.service-types.store', 'admin.cms.api.service-types.store'],
        'sort'  => 1,
    ],
    [
        'key'   => 'cms.service-types.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => ['admin.cms.service-types.edit', 'admin.cms.service-types.update', 'admin.cms.api.service-types.update'],
        'sort'  => 2,
    ],
    [
        'key'   => 'cms.service-types.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => ['admin.cms.service-types.delete', 'admin.cms.api.service-types.destroy'],
        'sort'  => 3,
    ],
    [
        'key'   => 'cms.service-types.restore',
        'name'  => 'cms::app.acl.restore',
        'route' => 'admin.cms.service-types.restore',
        'sort'  => 4,
    ],
    [
        'key'   => 'cms.service-types.forceDelete',
        'name'  => 'cms::app.acl.forceDelete',
        'route' => 'admin.cms.service-types.forceDelete',
        'sort'  => 5,
    ],
    [
        'key'   => 'cms.services',
        'name'  => 'cms::app.menu.services',
        'route' => ['admin.cms.services.index', 'admin.cms.api.services.index', 'admin.cms.api.services.show'],
        'sort'  => 15,
    ],
    [
        'key'   => 'cms.services.create',
        'name'  => 'cms::app.acl.create',
        'route' => ['admin.cms.services.create', 'admin.cms.services.store', 'admin.cms.api.services.store'],
        'sort'  => 1,
    ],
    [
        'key'   => 'cms.services.edit',
        'name'  => 'cms::app.acl.edit',
        'route' => ['admin.cms.services.edit', 'admin.cms.services.update', 'admin.cms.api.services.update'],
        'sort'  => 2,
    ],
    [
        'key'   => 'cms.services.delete',
        'name'  => 'cms::app.acl.delete',
        'route' => ['admin.cms.services.delete', 'admin.cms.api.services.destroy'],
        'sort'  => 3,
    ],
    [
        'key'   => 'cms.services.restore',
        'name'  => 'cms::app.acl.restore',
        'route' => 'admin.cms.services.restore',
        'sort'  => 4,
    ],
    [
        'key'   => 'cms.services.forceDelete',
        'name'  => 'cms::app.acl.forceDelete',
        'route' => 'admin.cms.services.forceDelete',
        'sort'  => 5,
    ],
];
